### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by NitroFuN** [WKS-uwu/DUCK#1]
sir pls script hotstar 8k dolby visoon plus

**Comment by WKS-uwu** [comment]
I invoked the best justsu I could perform, the result is that you need a Sony TV with AI in order to have 8K HDR and Dolby Vision
 -sasuke_duck

![image](https://cdn.discordapp.com/attachments/707710449398841506/916443550353338398/da5cd36c5be1caf08736996c18638d10950a7556v2_00.png)

**Comment by NitroFuN** [comment]
Thank you sir i respect your help sir
